Blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  scope '/(:locale)', defaults: { locale: 'en' }, constraints: { locale: /en|es/ } do
  resources :articles
  get  "welcome/index"
  root 'welcome#index'
end
=begin
  get "/articles" index
  post "/articles" create
  delete "/articles" delete
  get "/articles/:id" show
  get "/articles/new" new
  get "/articles/:id/edit" edit
  patch "/articles/:id" update
  put "/articles/:id" update
=end

  

end

Blog/app/models/article.rb
class Article < ActiveRecord::Base
  validates:title, presence: true, uniqueness: true
  validates:body, presence: true, length: { minimum: 20}
end

Blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
  	I18n.locale = params[:locale].to_sym
  end
  
end

Blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #GET /articles
  def index
    @articles = Article.all
  end
  #Get /articles/:id
  def show
    @article = Article.find(params[:id])
  end
  #GET /articles/new
  def new
    @article = Article.new
  end
  #POST /articles
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end
  def edit
    @article = Article.find(params[:id])
  end
  #GET /articles/:id
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  private

  def article_params
    params.require(:article).permit(:title,:body)
  end
end

Blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Blog/app/helpers/article_helper.rb
module ArticleHelper
end

Blog/app/helpers/welcome_controller_helper.rb
module WelcomeControllerHelper
end

Blog/app/views/articles/edit.html.erb
<h2>Editar Artículo</h2>
<%= render 'articles/partials/inputs' %>

Blog/app/views/articles/index.html.erb
<h2>Articulos</h2>
<br/>
<p class="btn btn-success"><%= link_to "Nuevo", "/articles/new"%></p>
<br/><br/>
<table class="table table-striped table-responsive">
  <tr class="info">
    <th><%= t('articles.title') %></th>
    <th><%= t('articles.body') %></th>
    <th width="10%"><%= t('articles.controls') %></th>
  </tr>
  <% @articles.each do |article|%>
   <tr>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
     <td>
       <div class="row">
         <div class="col-lg-4 col-md-4 col-xs-4 col-sm-4">
           <%= link_to "", article, class: "fa fa-eye"%>
         </div>
         <div class="col-lg-4 col-md-4 col-xs-4 col-sm-4">
           <%= link_to "", edit_article_path(@articles),class: "fa fa-pencil-square-o"%>
         </div>
         <div class="col-lg-4 col-md-4 col-xs-4 col-sm-4">
           <%= link_to "",article, method: :delete , class: "fa fa-trash"%>
         </div>
       </div>
     </td>
    </tr>
  <% end %>
</table>

Blog/app/views/articles/new.html.erb
<h2>Nuevo Artículo</h2>
<%= render 'articles/partials/inputs' %>

Blog/app/views/articles/partials/_inputs.html.erb
<%= form_for(@article) do |f| %>
    <% @article.errors.full_messages.each do |message| %>
        <div class="alert alert-danger" role="alert">
          * <%= message %>
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
          </button>
        </div>
    <% end %>

    <div class="row">
      <div class="col-lg-7">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control" %>
      </div>
    </div>
    <br/><br/>
    <div class="row">
      <div class="col-lg-3">
        <p><%= f.submit "Guardar", class: "btn btn-large btn-success" %></p>
      </div>
    </div>
<% end %>

Blog/app/views/articles/show.html.erb
<h2>Perfil de Artículo</h2>
<br/>
<div class="col-lg-10">
  <%= link_to "Editar ", edit_article_path(@article), class: "fa fa-pencil-square-o"%>
  </br>
  <h3><%= @article.title %></h3>
  <table cellspacing="10" width="100%">
    <tr>
      <td valign="top" width="20%">
        <p><b>Cuerpo</b></p>
      </td>
      <td width="80%">
        <p><%= @article.body %></p>
      </td>
    </tr>
    <tr>
      <td valign="top" width="20%">
        <p><b>Visitas</b></p>
      </td>
      <td width="80%">
        <p><%= @article.visits_count %></p>
      </td>
    </tr>
  </table>
</div>

Blog/app/views/generals/navs/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to  "Bienvenido", root_path %></li>
        <li><%= link_to  "Articulos", "/articles" %></li>
        <li><a href="#">Programación</a></li>
        <li><a href="#">Tecnología</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name=”viewport” content=”width=device-width, initial-scale=1”>
  <title>Blog</title>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" media="screen and (max-width: 480px)" href="mobile.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'generals/navs/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<div class="customizer-container">
  <% flash.each do |key, value| %>
    <p><%= value %></p>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

Blog/app/views/welcome/index.html.erb
<%# Nuestra primera página de Ruby Rails %>
<h1>Bienvenidos a Blog</h1>